import type { Metadata } from "next";
import { Suspense } from "react";
import "./globals.css";
import PocketbaseProvider from "./providers/pocketbase";
import TanstackQueryProvider from "./providers/tanstack-query";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <PocketbaseProvider>
          <TanstackQueryProvider>
            <Suspense>{children}</Suspense>
          </TanstackQueryProvider>
        </PocketbaseProvider>
        <div id="portal" className="w-full h-0 fixed"></div>
      </body>
    </html>
  );
}
